# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike_schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('distance', models.FloatField(blank=True, default=0, null=True)),
                ('route_type', models.CharField(blank=True, max_length=200, null=True)),
                ('elevation_gain', models.IntegerField(blank=True, default=0, null=True)),
                ('drive_distance', models.IntegerField(blank=True, default=0, null=True)),
                ('favorite', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('went', 'Went'), ('canceled', 'Canceled')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hike_schedule.Route'),
        ),
    ]
